server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:

          enabled: true
      routes:

        - id: product-service-route

          uri: lb://product-catalog-service
          predicates:

            - Path=/products/**

        - id: order-service-route
          uri: lb://order-simulation-service
          predicates:
            
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
