spring:

  application:
    name: product-catalog-service

  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password:


  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081


eureka:
  client:

    service-url:
      defaultZone: http://localhost:8761/eureka/
